<?php

namespace AppBundle\Repository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Doctrine\ORM\EntityRepository
{

    public function searchByAll($data)
    {
        $query = $this->createQueryBuilder('s')
            ->where("s.numberAccount LIKE '$data%'")
            ->getQuery()
            ->getResult();

        return $query;
    }
}
