<?php

namespace AppBundle\Repository;

/**
 * productPriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class productPriceRepository extends \Doctrine\ORM\EntityRepository
{
}
