<?php

namespace AppBundle\Repository;

/**
 * ProductsOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsOrderRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByOrderEmpty(){
        $query = $this->createQueryBuilder('o')
            ->where("o.orderId IS NULL")
            ->getQuery()
            ->getResult();

        return $query;
    }

    public function findProductId($idProduct) {
        $query = $this->createQueryBuilder('o')
            ->where("o.product = :idProduct")
            ->setParameter('idProduct', $idProduct )
            ->getQuery()
            ->getResult();

        return $query;
    }
}
