<?php

namespace AppBundle\Repository;

/**
 * ProductDefinitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductDefinitionRepository extends \Doctrine\ORM\EntityRepository
{
}
