fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

home:
    path: /{_locale}
    defaults: { _controller: AppBundle:Home:index }
    requirements:
        _locale: en|fr

set_name_user:
    path: /user/name
    defaults: { _controller: AppBundle:User:setName }

set_email_user:
    path: /user/email
    defaults: { _controller: AppBundle:User:setMail }


################################customer##############################

customer_index:
    path: /{_locale}/customers/index
    defaults: { _controller: AppBundle:Customer:index }

customer_create:
    path: /{_locale}/customer/create
    defaults: { _controller: AppBundle:Customer:create }
    requirements:
        _locale: en|fr

customer_update:
    path: /customer/update/{id}
    defaults: { _controller: AppBundle:Customer:update }
    requirements:
        page: '\d+'

customer_delete:
    path: /customer/delete/{id}
    defaults: { _controller: AppBundle:Customer:delete }
    requirements:
        page: '\d+'

customer_index_by_costumer:
    path: /{_locale}/customer/show/{id}
    defaults: { _controller: AppBundle:Customer:indexByCustomer }
    requirements:
        _locale: en|fr
        page: '\d+'

customer_sort:
    path: /customer/sort
    defaults: { _controller: AppBundle:Customer:sort }

customer_search:
    path: /customer/search
    defaults: { _controller: AppBundle:Customer:search }

pdf_by_customer:
    path: /customer/pdf/{customer}
    defaults: { _controller: AppBundle:Customer:pdf }
    requirements:
        customer: '\d+'

################################product##############################

product_index:
    path: /{_locale}/products/index
    defaults: { _controller: AppBundle:Product:index }
    requirements:
        _locale: en|fr

product_create:
    path: /{_locale}/product/create
    defaults: { _controller: AppBundle:Product:create }
    requirements:
        _locale: en|fr

product_update:
   path: /{_locale}/product/update/{id}
   defaults: { _controller: AppBundle:Product:update }
   requirements:
      _locale: en|fr
      id: '\d+'

product_delete:
   path: /product/delete/{id}
   defaults: { _controller: AppBundle:Product:delete }
   requirements:
         id: '\d+'

product_index_by_product:
   path: /{_locale}/product/show/{id}
   defaults: { _controller: AppBundle:Product:indexByCustomer }
   requirements:
         _locale: en|fr
         id: '\d+'

product_search:
    path: /product/search
    defaults: { _controller: AppBundle:Product:search }


product_import:
  path: /products/import
  defaults: { _controller: AppBundle:Files:importProducts }

################################order##############################

orderCustomer_index:
    path: /{_locale}/ordersCustomer/index
    defaults: { _controller: AppBundle:OrderCustomer:index }
    requirements:
        _locale: en|fr

orderCustomer_create:
    path: /{_locale}/orderCustomer/create/{id}
    defaults: { _controller: AppBundle:OrderCustomer:create }
    requirements:
        _locale: en|fr
        id: '\d+'

orderCustomer_update:
   path: /orderCustomer/update/{id}
   defaults: { _controller: AppBundle:OrderCustomer:update }
   requirements:
      id: '\d+'

orderCustomer_delete:
   path: /orderCustomer/delete/{id}
   defaults: { _controller: AppBundle:OrderCustomer:delete }
   requirements:
         id: '\d+'

orderCustomer_index_by_orderCustomer:
   path: /{_locale}/orderCustomer/show/product/{id}
   defaults: { _controller: AppBundle:OrderCustomer:indexByOrderCustomer }
   requirements:
         id: '\d+'

order_insert_product:
   path: /order/product/insert
   defaults: { _controller: AppBundle:OrderCustomer:insertProduct }

order_update_price:
   path: /order/product/update/price
   defaults: { _controller: AppBundle:OrderCustomer:updatePrice }

order_update_quantity:
   path: /order/product/update/quantity
   defaults: { _controller: AppBundle:OrderCustomer:updateQuantity }

order_product_delete:
  path: /order/product/delete
  defaults: { _controller: AppBundle:OrderCustomer:deleteProduct }

pdf_by_order:
  path: /order/pdf/{orderCustomer}
  defaults: { _controller: AppBundle:OrderCustomer:pdf }
  requirements:
    orderCustomer: '\d+'

################################statistical##############################

statistical_list:
  path: /statistical/index
  defaults: { _controller: AppBundle:Statistical:index }

################################statistical##############################
import_cutomer:
   path: /import/customer
   defaults: { _controller: AppBundle:Files:importCustomer }

export_cutomer:
   path: /export/customer
   defaults: { _controller: AppBundle:Files:exportCustomer }

import_order:
   path: /import/customer
   defaults: { _controller: AppBundle:Files:importCustomer }

export_order:
   path: /export/customer
   defaults: { _controller: AppBundle:Files:exportCustomer }

####################################goal##################################

goal_update:
   path: /{_locale}/goal/update
   defaults: { _controller: AppBundle:Goal:update }