fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

home:
    path: /
    defaults: { _controller: AppBundle:Home:index }

customer_index:
    path: /customer/index
    defaults: { _controller: AppBundle:Customer:index }

customer_create:
    path: /customer/create
    defaults: { _controller: AppBundle:Customer:create }

customer_update:
    path: /customer/update/{id}
    defaults: { _controller: AppBundle:Customer:update }
    requirements:
        page: '\d+'

customer_delete:
    path: /customer/delete/{id}
    defaults: { _controller: AppBundle:Customer:delete }
    requirements:
        page: '\d+'

customer_index_by_costumer:
    path: /customer/show/customer/{id}
    defaults: { _controller: AppBundle:Customer:indexByCustomer }
    requirements:
        page: '\d+'

################################product##############################

product_index:
    path: /products/index
    defaults: { _controller: AppBundle:Product:index }

product_create:
    path: /product/create
    defaults: { _controller: AppBundle:Product:create }

product_update:
   path: /product/update/{id}
   defaults: { _controller: AppBundle:Product:update }
   requirements:
      id: '\d+'

product_delete:
   path: /product/delete/{id}
   defaults: { _controller: AppBundle:Product:delete }
   requirements:
         id: '\d+'

product_index_by_product:
   path: /product/show/product/{id}
   defaults: { _controller: AppBundle:Product:indexByCustomer }
   requirements:
         id: '\d+'

################################order##############################

orderCustomer_index:
    path: /orderCustomer/index
    defaults: { _controller: AppBundle:OrderCustomer:index }

orderCustomer_create:
    path: /orderCustomer/create
    defaults: { _controller: AppBundle:OrderCustomer:create }

orderCustomer_update:
   path: /orderCustomer/update/{id}
   defaults: { _controller: AppBundle:OrderCustomer:update }
   requirements:
      id: '\d+'

orderCustomer_delete:
   path: /orderCustomer/delete/{id}
   defaults: { _controller: AppBundle:OrderCustomer:delete }
   requirements:
         id: '\d+'

orderCustomer_index_by_orderCustomer:
   path: /orderCustomer/show/product/{id}
   defaults: { _controller: AppBundle:OrderCustomer:indexByCustomer }
   requirements:
         id: '\d+'